name: Minimal Upload Artifact Test

on:
  push:
    branches:
      - main

jobs:
  test-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create test file
        run: |
          echo "This is a test file" > testfile.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-artifact
          path: testfile.txt
