name: Run JMeter Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre-headless
        wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.5.tgz
        tar -xzf apache-jmeter-5.5.tgz
        mv apache-jmeter-5.5 jmeter

    - name: Run JMeter Test Plan
      run: |
        ./jmeter/bin/jmeter -n -t blazedemo_test_plan.jmx -l results.jtl

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-results
        path: results.jtl
