name: Run JMeter Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Updated to the latest version

    - name: Set up JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre-headless
        wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xzf apache-jmeter-5.6.3.tgz
        mv apache-jmeter-5.6.3 jmeter

    - name: Debug JMeter Directory
        run: |
          ls -R
          ls -R jmeter

    - name: Run JMeter Test Plan
      run: |
        ./jmeter/bin/jmeter -n -t jmeter/blazedemo_test_plan.jmx -l results.jtl

    - name: Upload Test Results
      uses: actions/upload-artifact@v4 # Updated to the latest version
      with:
        name: jmeter-results
        path: results.jtl
